
CREATE USER "HERNAN" IDENTIFIED BY "Hernamstein3" DEFAULT TABLESPACE "USERS" QUOTA UNLIMITED ON "USERS" ; 
ALTER SESSION SET CURRENT_SCHEMA="HERNAN";

CREATE SEQUENCE sequence_documents
MINVALUE 0
START WITH 0
INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE sequence_animals
MINVALUE 0
START WITH 0
INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE "TYPES_DOCUMENTS" (
	ID INTEGER,
	NAME NVARCHAR2(100),
	DESCRIPTION NVARCHAR2(100),
	CONSTRAINT TYPES_DOCUMENTS_PK PRIMARY KEY (ID) 
);

CREATE TABLE "TYPES_BOVINES" (
	ID INTEGER,
	NAME NVARCHAR2(100),
	DESCRIPTION NVARCHAR2(100),
	CONSTRAINT TYPES_BOVINES_PK PRIMARY KEY (ID) 
);

CREATE TABLE "DOCUMENTS" (
	ID INTEGER,
	NAME NVARCHAR2(100),
	DESCRIPTION NVARCHAR2(100),
	TYPE INTEGER,
	CONSTRAINT DOCUMENTS_PK PRIMARY KEY (ID), 
	FOREIGN KEY(TYPE) REFERENCES TYPES_DOCUMENTS(ID)
);

CREATE TABLE "BOVINES" (
	ID INTEGER,
	NAME NVARCHAR2(100),
	DATE_BIRTH DATE,
	SEX NVARCHAR2(100),
	TYPE INTEGER,
	MOTHER INTEGER,
	COLOR NVARCHAR2(100),
	STATE NVARCHAR2(100),
	DATE_SALE DATE,
	CONSTRAINT BOVINES_PK PRIMARY KEY (ID) 
);

--ALTER SESSION SET NLS_DATE_LANGUAGE='ENGLISH'
--alter session set nls_date_format = 'DD/MM/YYYY';

--INICIO INSERTS DE PRUEBA. QUITAR AL COMITEAR--



--FIN INSERTS PROPIOS--

ALTER TABLE "BOVINES"
ADD FOREIGN KEY (MOTHER) REFERENCES BOVINES(ID);

CREATE TABLE "IDENTIFIERS" (
	DIIO NVARCHAR2(10),
	BOVINE_ID INTEGER,
	DATE_PLACEMENT DATE,
	STATE NVARCHAR2(100),
	CONSTRAINT DIIO_PK PRIMARY KEY (DIIO)
	--CONSTRAINT BOVINE_ID_FK FOREIGN KEY (BOVINE_ID) REFERENCES BOVINES (ID)
);

ALTER TABLE "IDENTIFIERS"
ADD FOREIGN KEY (BOVINE_ID) REFERENCES BOVINES(ID);

--INSERT ARETES. Quitar al comitear


--FIN INSERT ARETES

CREATE TABLE "USERS" (
	ID INTEGER,
	NAME NVARCHAR2(100),
	PASSWORD NVARCHAR2(100),
	CONSTRAINT USERS_PK PRIMARY KEY (ID) 
);

INSERT INTO "USERS" (ID,NAME,PASSWORD) values (1,'hernan@correo.com','12345');
INSERT INTO "TYPES_DOCUMENTS" (ID,NAME,DESCRIPTION) values (1,'Formulario','Documento para el ingreso de información');
INSERT INTO "TYPES_BOVINES" (ID,NAME,DESCRIPTION) VALUES (1,'Ternero',NULL);
INSERT INTO "TYPES_BOVINES" (ID,NAME,DESCRIPTION) VALUES (2,'Ternera',NULL);
INSERT INTO "TYPES_BOVINES" (ID,NAME,DESCRIPTION) VALUES (3,'Toro',NULL);
INSERT INTO "TYPES_BOVINES" (ID,NAME,DESCRIPTION) VALUES (4,'Vaquilla',NULL);
INSERT INTO "TYPES_BOVINES" (ID,NAME,DESCRIPTION) VALUES (5,'Vaca',NULL);
INSERT INTO "TYPES_BOVINES" (ID,NAME,DESCRIPTION) VALUES (6,'Buey',NULL);
INSERT INTO "TYPES_BOVINES" (ID,NAME,DESCRIPTION) VALUES (7,'Novillo',NULL);
INSERT INTO "DOCUMENTS" (ID,NAME,DESCRIPTION,TYPE) values (sequence_documents.nextval,'FMA','Formulario emitido por el SAG para el traslado de animales',1);
--INSERT INTO "BOVINES" (ID,NAME,DATE_BIRTH,SEX,TYPE,MOTHER,COLOR,STATE,DATE_SALE) values (1,'Vaca amarilla','2023-12-05','hembra','vaca',1,'Amarillo','Vivo','2023-12-05');

